### ISSUE TITLE
DPL-1019 - As a team lead (Liz) I would like to be able to upload tapestation quants for so we can download the quantfile from limber to support pooling for the scRNA pipeline

### ISSUE THREAD

**Issue by stevieing** [sanger/quanthub#283]
**User story**
As a team lead (Liz) I would like to be able to upload tapestation quants for so we can download the quantfile from limber to support pooling

**Who are the primary contacts for this story**
Liz / Katy / Steve

**Who is the nominated tester for UAT**
Liz

**Acceptance criteria**
To be considered successful the solution must allow:
- [x] when visiting quanthub there should be a qc assay type
- [x] ability to upload a tapstation quant and export to Sequencescape
- [x] ability to download quants from Limber

**Dependencies**
This story is blocked by the following dependencies:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

References
This story has a non-blocking relationship with:
- #<issue_no.>
- sanger/<repo>#<issue_no.>

**Additional context**

**Comment by KatyTaylor** [comment]
I removed the references to the scRNA cDNA Prep  / 007c pipeline, because I believe this refers to the existing scRNA pipeline instead.

**Comment by dasunpubudumal** [comment]
Update: 

Some modifications are required because scRNA TubeStations return well IDs for `Sample Description` attribute in the CSV instead of tubes. This needs to be handled differently. 

Modify the existing logic to fit the following pattern:

- [ ] Use `FileName` to parse and return the plate ID.
- [ ] Use `Sample Description` to figure out the asset ID.

Use the `asset_id` when exporting to Sequencescape.
